[package]
name = "pallet-ipfs"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Unlicense"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME example pallet"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
frame-support = { version = "4.0.0-dev", default-features = false, path = "../../../../frame/support" }
frame-system = { version = "4.0.0-dev", default-features = false, path = "../../../../frame/system" }
pallet-balances = { version = "4.0.0-dev", default-features = false, path = "../../../../frame/balances" }
sp-runtime = { version = "6.0.0", default-features = false, path = "../../../../primitives/runtime" }
sp-std = { version = "4.0.0", default-features = false, path = "../../../../primitives/std" }
sp-io = { version = "6.0.0", default-features = false, path = "../../../../primitives/io" }
sp-core = { default-features = false, version = "6.0.0", path = "../../../../primitives/core" }
frame-benchmarking = { version = "4.0.0-dev", default-features = false, path = "../../../../frame/benchmarking", optional = true }
log = { version = "0.4.17", default-features = false }
sp-keystore = { version = "0.12.0", path = "../../../../primitives/keystore", optional = true }
pallet-assets = { version = "4.0.0-dev", default-features = false, path = "../../../../frame/assets" }
serde = { version = "1.0.136", default-features = false }
sp-application-crypto = { version = "6.0.0", path = "../../../../primitives/application-crypto", default-features = false }

[dev-dependencies]
sp-core = { version = "6.0.0", path = "../../../../primitives/core", default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"pallet-balances/std",
	"scale-info/std",
	"sp-io/std",
	"sp-keystore/std",
	"sp-application-crypto/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
	'pallet-assets/std',
	'pallet-balances/std',
]
runtime-benchmarks = ["frame-benchmarking"]
try-runtime = ["frame-support/try-runtime"]
