[package]
name = "pallet-bags-list-fuzzer"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Fuzzer for FRAME pallet bags list"
readme = "README.md"
publish = false

[dependencies]
honggfuzz = "0.5"
rand = { version = "0.8", features = ["std", "small_rng"] }
frame-election-provider-support = { version = "4.0.0-dev", path = "../../election-provider-support" }
# NOTE: These `runtime-benchmarks` dependencies here are clearly wrong.
# However it has always been the case through transitive feature bleeding.
# Since that is now fixed it needs to be happen explicitly and looks ugly.
# The underlying reason is that `StakingMock::set_score_of` is only available in 
# benchmarking and tests, which is called by `ExtBuilder::build_and_execute`.
pallet-bags-list = { version = "4.0.0-dev", features = ["fuzz", "runtime-benchmarks"], path = ".." }
pallet-collective = { version = "4.0.0-dev", features = ["runtime-benchmarks"], path = "../../collective" }
pallet-referenda = { version = "4.0.0-dev", features = ["runtime-benchmarks"], path = "../../referenda" }
pallet-conviction-voting = { version = "4.0.0-dev", features = ["runtime-benchmarks"], path = "../../conviction-voting" }
pallet-ranked-collective = { version = "4.0.0-dev", features = ["runtime-benchmarks"], path = "../../ranked-collective" }

[[bin]]
name = "bags-list"
path = "src/main.rs"
